name: .NET

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2
    - name: Restore dependencies
      run: dotnet restore APICsharp/APIFilR.sln
    - name: Build
      run: dotnet build APICsharp/APIFilR.sln --no-restore
    - name: Test
      run: dotnet test APICsharp/APIFilR.sln --no-build --verbosity normal
